package com.aegis.cluster

/** Prompt assembly for aggregated incident briefings (4D.3).
  *
  * Folds a multi-agent incident into a single briefing instead of one
  * briefing per sentinel (alert-storm reduction). Reuses the existing
  * [[BriefingPrompt]]/[[Llm]] machinery via a synthetic anomaly so the
  * aggregated briefing is generated by the same pipeline as per-agent
  * briefings.
  */
object IncidentPrompts {

  def build(inc: Incident, evidence: Seq[String]): BriefingPrompt = {
    val synthetic = AnomalyEventBus.AnomalyEvent(
      agentId = inc.agents.mkString(","),
      eventType = inc.eventType,
      description = s"${inc.agents.size} agents affected simultaneously",
      severity = inc.maxSeverity,
      score = 0.0,
      timestampNs = inc.endNs
    )

    val text =
      s"""You are an SRE diagnostic assistant for the Aegis telemetry platform.
         |Produce a concise incident briefing. Structure your answer with:
         |## Root-Cause Hypothesis
         |## Timeline
         |## Related Context
         |## Suggested Actions
         |
         |Incident:
         |- signature: ${inc.eventType}
         |- affected agents: ${inc.agents.mkString(", ")}
         |- severity: ${inc.maxSeverity}
         |- window: ${Briefing.ts(inc.startNs)} -> ${Briefing.ts(inc.endNs)}
         |
         |Per-agent evidence (oldest first):
         |${evidence.mkString("\n")}
         |""".stripMargin

    BriefingPrompt(synthetic, evidence, Seq.empty, text)
  }
}
