// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: v1/telemetry.proto

package telemetryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkPayload_Direction int32

const (
	NetworkPayload_INBOUND  NetworkPayload_Direction = 0
	NetworkPayload_OUTBOUND NetworkPayload_Direction = 1
)

// Enum value maps for NetworkPayload_Direction.
var (
	NetworkPayload_Direction_name = map[int32]string{
		0: "INBOUND",
		1: "OUTBOUND",
	}
	NetworkPayload_Direction_value = map[string]int32{
		"INBOUND":  0,
		"OUTBOUND": 1,
	}
)

func (x NetworkPayload_Direction) Enum() *NetworkPayload_Direction {
	p := new(NetworkPayload_Direction)
	*p = x
	return p
}

func (x NetworkPayload_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkPayload_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_telemetry_proto_enumTypes[0].Descriptor()
}

func (NetworkPayload_Direction) Type() protoreflect.EnumType {
	return &file_v1_telemetry_proto_enumTypes[0]
}

func (x NetworkPayload_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkPayload_Direction.Descriptor instead.
func (NetworkPayload_Direction) EnumDescriptor() ([]byte, []int) {
	return file_v1_telemetry_proto_rawDescGZIP(), []int{4, 0}
}

type AnomalyEvent_Severity int32

const (
	AnomalyEvent_INFO     AnomalyEvent_Severity = 0
	AnomalyEvent_WARNING  AnomalyEvent_Severity = 1
	AnomalyEvent_CRITICAL AnomalyEvent_Severity = 2
)

// Enum value maps for AnomalyEvent_Severity.
var (
	AnomalyEvent_Severity_name = map[int32]string{
		0: "INFO",
		1: "WARNING",
		2: "CRITICAL",
	}
	AnomalyEvent_Severity_value = map[string]int32{
		"INFO":     0,
		"WARNING":  1,
		"CRITICAL": 2,
	}
)

func (x AnomalyEvent_Severity) Enum() *AnomalyEvent_Severity {
	p := new(AnomalyEvent_Severity)
	*p = x
	return p
}

func (x AnomalyEvent_Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnomalyEvent_Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_telemetry_proto_enumTypes[1].Descriptor()
}

func (AnomalyEvent_Severity) Type() protoreflect.EnumType {
	return &file_v1_telemetry_proto_enumTypes[1]
}

func (x AnomalyEvent_Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnomalyEvent_Severity.Descriptor instead.
func (AnomalyEvent_Severity) EnumDescriptor() ([]byte, []int) {
	return file_v1_telemetry_proto_rawDescGZIP(), []int{5, 0}
}

type TelemetryResponse_Action int32

const (
	TelemetryResponse_ACK               TelemetryResponse_Action = 0
	TelemetryResponse_SLOW_DOWN         TelemetryResponse_Action = 1
	TelemetryResponse_FLUSH_NOW         TelemetryResponse_Action = 2
	TelemetryResponse_RESUME            TelemetryResponse_Action = 3
	TelemetryResponse_DROP_LOW_PRIORITY TelemetryResponse_Action = 4
)

// Enum value maps for TelemetryResponse_Action.
var (
	TelemetryResponse_Action_name = map[int32]string{
		0: "ACK",
		1: "SLOW_DOWN",
		2: "FLUSH_NOW",
		3: "RESUME",
		4: "DROP_LOW_PRIORITY",
	}
	TelemetryResponse_Action_value = map[string]int32{
		"ACK":               0,
		"SLOW_DOWN":         1,
		"FLUSH_NOW":         2,
		"RESUME":            3,
		"DROP_LOW_PRIORITY": 4,
	}
)

func (x TelemetryResponse_Action) Enum() *TelemetryResponse_Action {
	p := new(TelemetryResponse_Action)
	*p = x
	return p
}

func (x TelemetryResponse_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TelemetryResponse_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_telemetry_proto_enumTypes[2].Descriptor()
}

func (TelemetryResponse_Action) Type() protoreflect.EnumType {
	return &file_v1_telemetry_proto_enumTypes[2]
}

func (x TelemetryResponse_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TelemetryResponse_Action.Descriptor instead.
func (TelemetryResponse_Action) EnumDescriptor() ([]byte, []int) {
	return file_v1_telemetry_proto_rawDescGZIP(), []int{6, 0}
}

// Metadata attached to every request from an agent.
type AgentMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	KernelVersion string                 `protobuf:"bytes,4,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,5,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMetadata) Reset() {
	*x = AgentMetadata{}
	mi := &file_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMetadata) ProtoMessage() {}

func (x *AgentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMetadata.ProtoReflect.Descriptor instead.
func (*AgentMetadata) Descriptor() ([]byte, []int) {
	return file_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMetadata) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMetadata) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentMetadata) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentMetadata) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *AgentMetadata) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

// Data envelope that can hold different types of events.
// Agents send one or more payloads per stream message.
type TelemetryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Agent *AgentMetadata         `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TelemetryRequest_Metric
	//	*TelemetryRequest_Syscall
	//	*TelemetryRequest_Network
	//	*TelemetryRequest_Anomaly
	Payload       isTelemetryRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryRequest) Reset() {
	*x = TelemetryRequest{}
	mi := &file_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRequest) ProtoMessage() {}

func (x *TelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRequest.ProtoReflect.Descriptor instead.
func (*TelemetryRequest) Descriptor() ([]byte, []int) {
	return file_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryRequest) GetAgent() *AgentMetadata {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *TelemetryRequest) GetPayload() isTelemetryRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TelemetryRequest) GetMetric() *MetricPayload {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryRequest_Metric); ok {
			return x.Metric
		}
	}
	return nil
}

func (x *TelemetryRequest) GetSyscall() *SyscallPayload {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryRequest_Syscall); ok {
			return x.Syscall
		}
	}
	return nil
}

func (x *TelemetryRequest) GetNetwork() *NetworkPayload {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryRequest_Network); ok {
			return x.Network
		}
	}
	return nil
}

func (x *TelemetryRequest) GetAnomaly() *AnomalyEvent {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryRequest_Anomaly); ok {
			return x.Anomaly
		}
	}
	return nil
}

type isTelemetryRequest_Payload interface {
	isTelemetryRequest_Payload()
}

type TelemetryRequest_Metric struct {
	Metric *MetricPayload `protobuf:"bytes,2,opt,name=metric,proto3,oneof"`
}

type TelemetryRequest_Syscall struct {
	Syscall *SyscallPayload `protobuf:"bytes,3,opt,name=syscall,proto3,oneof"`
}

type TelemetryRequest_Network struct {
	Network *NetworkPayload `protobuf:"bytes,4,opt,name=network,proto3,oneof"`
}

type TelemetryRequest_Anomaly struct {
	Anomaly *AnomalyEvent `protobuf:"bytes,5,opt,name=anomaly,proto3,oneof"`
}

func (*TelemetryRequest_Metric) isTelemetryRequest_Payload() {}

func (*TelemetryRequest_Syscall) isTelemetryRequest_Payload() {}

func (*TelemetryRequest_Network) isTelemetryRequest_Payload() {}

func (*TelemetryRequest_Anomaly) isTelemetryRequest_Payload() {}

// Standard system-level metrics sampled at a configurable interval.
type MetricPayload struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CpuUsagePercent     float64                `protobuf:"fixed64,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsagePercent  float64                `protobuf:"fixed64,2,opt,name=memory_usage_percent,json=memoryUsagePercent,proto3" json:"memory_usage_percent,omitempty"`
	MemoryUsedBytes     int64                  `protobuf:"varint,3,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes    int64                  `protobuf:"varint,4,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	ActiveConnections   int32                  `protobuf:"varint,5,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	OpenFileDescriptors int32                  `protobuf:"varint,6,opt,name=open_file_descriptors,json=openFileDescriptors,proto3" json:"open_file_descriptors,omitempty"`
	DiskIoReadBytesSec  float64                `protobuf:"fixed64,7,opt,name=disk_io_read_bytes_sec,json=diskIoReadBytesSec,proto3" json:"disk_io_read_bytes_sec,omitempty"`
	DiskIoWriteBytesSec float64                `protobuf:"fixed64,8,opt,name=disk_io_write_bytes_sec,json=diskIoWriteBytesSec,proto3" json:"disk_io_write_bytes_sec,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MetricPayload) Reset() {
	*x = MetricPayload{}
	mi := &file_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPayload) ProtoMessage() {}

func (x *MetricPayload) ProtoReflect() protoreflect.Message {
	mi := &file_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPayload.ProtoReflect.Descriptor instead.
func (*MetricPayload) Descriptor() ([]byte, []int) {
	return file_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *MetricPayload) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *MetricPayload) GetMemoryUsagePercent() float64 {
	if x != nil {
		return x.MemoryUsagePercent
	}
	return 0
}

func (x *MetricPayload) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *MetricPayload) GetMemoryTotalBytes() int64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *MetricPayload) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *MetricPayload) GetOpenFileDescriptors() int32 {
	if x != nil {
		return x.OpenFileDescriptors
	}
	return 0
}

func (x *MetricPayload) GetDiskIoReadBytesSec() float64 {
	if x != nil {
		return x.DiskIoReadBytesSec
	}
	return 0
}

func (x *MetricPayload) GetDiskIoWriteBytesSec() float64 {
	if x != nil {
		return x.DiskIoWriteBytesSec
	}
	return 0
}

// Captured syscall event from eBPF or ptrace.
type SyscallPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyscallName   string                 `protobuf:"bytes,1,opt,name=syscall_name,json=syscallName,proto3" json:"syscall_name,omitempty"`
	Pid           int64                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Tid           int64                  `protobuf:"varint,3,opt,name=tid,proto3" json:"tid,omitempty"`
	DurationNs    int64                  `protobuf:"varint,4,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	ReturnCode    int32                  `protobuf:"varint,5,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	Arguments     []byte                 `protobuf:"bytes,6,opt,name=arguments,proto3" json:"arguments,omitempty"`
	StackTrace    string                 `protobuf:"bytes,7,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyscallPayload) Reset() {
	*x = SyscallPayload{}
	mi := &file_v1_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyscallPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyscallPayload) ProtoMessage() {}

func (x *SyscallPayload) ProtoReflect() protoreflect.Message {
	mi := &file_v1_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyscallPayload.ProtoReflect.Descriptor instead.
func (*SyscallPayload) Descriptor() ([]byte, []int) {
	return file_v1_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *SyscallPayload) GetSyscallName() string {
	if x != nil {
		return x.SyscallName
	}
	return ""
}

func (x *SyscallPayload) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SyscallPayload) GetTid() int64 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *SyscallPayload) GetDurationNs() int64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

func (x *SyscallPayload) GetReturnCode() int32 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *SyscallPayload) GetArguments() []byte {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *SyscallPayload) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

// Network-level event (connection, packet, DNS).
type NetworkPayload struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	LocalAddress     string                   `protobuf:"bytes,1,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	LocalPort        int32                    `protobuf:"varint,2,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	RemoteAddress    string                   `protobuf:"bytes,3,opt,name=remote_address,json=remoteAddress,proto3" json:"remote_address,omitempty"`
	RemotePort       int32                    `protobuf:"varint,4,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	Protocol         string                   `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Direction        NetworkPayload_Direction `protobuf:"varint,6,opt,name=direction,proto3,enum=aegis.telemetry.v1.NetworkPayload_Direction" json:"direction,omitempty"`
	BytesTransferred int64                    `protobuf:"varint,7,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	LatencyNs        int64                    `protobuf:"varint,8,opt,name=latency_ns,json=latencyNs,proto3" json:"latency_ns,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NetworkPayload) Reset() {
	*x = NetworkPayload{}
	mi := &file_v1_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPayload) ProtoMessage() {}

func (x *NetworkPayload) ProtoReflect() protoreflect.Message {
	mi := &file_v1_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPayload.ProtoReflect.Descriptor instead.
func (*NetworkPayload) Descriptor() ([]byte, []int) {
	return file_v1_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkPayload) GetLocalAddress() string {
	if x != nil {
		return x.LocalAddress
	}
	return ""
}

func (x *NetworkPayload) GetLocalPort() int32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *NetworkPayload) GetRemoteAddress() string {
	if x != nil {
		return x.RemoteAddress
	}
	return ""
}

func (x *NetworkPayload) GetRemotePort() int32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *NetworkPayload) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NetworkPayload) GetDirection() NetworkPayload_Direction {
	if x != nil {
		return x.Direction
	}
	return NetworkPayload_INBOUND
}

func (x *NetworkPayload) GetBytesTransferred() int64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

func (x *NetworkPayload) GetLatencyNs() int64 {
	if x != nil {
		return x.LatencyNs
	}
	return 0
}

// Anomaly event detected by the agent's local analytics.
type AnomalyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Severity      AnomalyEvent_Severity  `protobuf:"varint,3,opt,name=severity,proto3,enum=aegis.telemetry.v1.AnomalyEvent_Severity" json:"severity,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnomalyEvent) Reset() {
	*x = AnomalyEvent{}
	mi := &file_v1_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnomalyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyEvent) ProtoMessage() {}

func (x *AnomalyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyEvent.ProtoReflect.Descriptor instead.
func (*AnomalyEvent) Descriptor() ([]byte, []int) {
	return file_v1_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *AnomalyEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AnomalyEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AnomalyEvent) GetSeverity() AnomalyEvent_Severity {
	if x != nil {
		return x.Severity
	}
	return AnomalyEvent_INFO
}

func (x *AnomalyEvent) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *AnomalyEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// The response from the brain, containing backpressure or control signals.
type TelemetryResponse struct {
	state   protoimpl.MessageState   `protogen:"open.v1"`
	Action  TelemetryResponse_Action `protobuf:"varint,1,opt,name=action,proto3,enum=aegis.telemetry.v1.TelemetryResponse_Action" json:"action,omitempty"`
	Message string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Suggested send interval in milliseconds when SLOW_DOWN is active.
	ThrottleIntervalMs int32 `protobuf:"varint,3,opt,name=throttle_interval_ms,json=throttleIntervalMs,proto3" json:"throttle_interval_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TelemetryResponse) Reset() {
	*x = TelemetryResponse{}
	mi := &file_v1_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryResponse) ProtoMessage() {}

func (x *TelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryResponse.ProtoReflect.Descriptor instead.
func (*TelemetryResponse) Descriptor() ([]byte, []int) {
	return file_v1_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *TelemetryResponse) GetAction() TelemetryResponse_Action {
	if x != nil {
		return x.Action
	}
	return TelemetryResponse_ACK
}

func (x *TelemetryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TelemetryResponse) GetThrottleIntervalMs() int32 {
	if x != nil {
		return x.ThrottleIntervalMs
	}
	return 0
}

// Request to flush a specific agent's ring buffer.
type FlushRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AgentId     string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	StartTimeNs int64                  `protobuf:"varint,2,opt,name=start_time_ns,json=startTimeNs,proto3" json:"start_time_ns,omitempty"`
	EndTimeNs   int64                  `protobuf:"varint,3,opt,name=end_time_ns,json=endTimeNs,proto3" json:"end_time_ns,omitempty"`
	// If empty, flush the full 60s window.
	EventTypes []string `protobuf:"bytes,4,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	// Maximum bytes to return (0 = unlimited).
	MaxBytes      int64 `protobuf:"varint,5,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushRequest) Reset() {
	*x = FlushRequest{}
	mi := &file_v1_telemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushRequest) ProtoMessage() {}

func (x *FlushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_telemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushRequest.ProtoReflect.Descriptor instead.
func (*FlushRequest) Descriptor() ([]byte, []int) {
	return file_v1_telemetry_proto_rawDescGZIP(), []int{7}
}

func (x *FlushRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FlushRequest) GetStartTimeNs() int64 {
	if x != nil {
		return x.StartTimeNs
	}
	return 0
}

func (x *FlushRequest) GetEndTimeNs() int64 {
	if x != nil {
		return x.EndTimeNs
	}
	return 0
}

func (x *FlushRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *FlushRequest) GetMaxBytes() int64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

// Chunked response for large flush payloads.
type FlushChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	TotalSize     int64                  `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	IsLast        bool                   `protobuf:"varint,4,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushChunk) Reset() {
	*x = FlushChunk{}
	mi := &file_v1_telemetry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushChunk) ProtoMessage() {}

func (x *FlushChunk) ProtoReflect() protoreflect.Message {
	mi := &file_v1_telemetry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushChunk.ProtoReflect.Descriptor instead.
func (*FlushChunk) Descriptor() ([]byte, []int) {
	return file_v1_telemetry_proto_rawDescGZIP(), []int{8}
}

func (x *FlushChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FlushChunk) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *FlushChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FlushChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

var File_v1_telemetry_proto protoreflect.FileDescriptor

const file_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x12v1/telemetry.proto\x12\x12aegis.telemetry.v1\"\xa0\x01\n" +
	"\rAgentMetadata\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12%\n" +
	"\x0ekernel_version\x18\x04 \x01(\tR\rkernelVersion\x12!\n" +
	"\ftimestamp_ns\x18\x05 \x01(\x03R\vtimestampNs\"\xd1\x02\n" +
	"\x10TelemetryRequest\x127\n" +
	"\x05agent\x18\x01 \x01(\v2!.aegis.telemetry.v1.AgentMetadataR\x05agent\x12;\n" +
	"\x06metric\x18\x02 \x01(\v2!.aegis.telemetry.v1.MetricPayloadH\x00R\x06metric\x12>\n" +
	"\asyscall\x18\x03 \x01(\v2\".aegis.telemetry.v1.SyscallPayloadH\x00R\asyscall\x12>\n" +
	"\anetwork\x18\x04 \x01(\v2\".aegis.telemetry.v1.NetworkPayloadH\x00R\anetwork\x12<\n" +
	"\aanomaly\x18\x05 \x01(\v2 .aegis.telemetry.v1.AnomalyEventH\x00R\aanomalyB\t\n" +
	"\apayload\"\x94\x03\n" +
	"\rMetricPayload\x12*\n" +
	"\x11cpu_usage_percent\x18\x01 \x01(\x01R\x0fcpuUsagePercent\x120\n" +
	"\x14memory_usage_percent\x18\x02 \x01(\x01R\x12memoryUsagePercent\x12*\n" +
	"\x11memory_used_bytes\x18\x03 \x01(\x03R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x04 \x01(\x03R\x10memoryTotalBytes\x12-\n" +
	"\x12active_connections\x18\x05 \x01(\x05R\x11activeConnections\x122\n" +
	"\x15open_file_descriptors\x18\x06 \x01(\x05R\x13openFileDescriptors\x122\n" +
	"\x16disk_io_read_bytes_sec\x18\a \x01(\x01R\x12diskIoReadBytesSec\x124\n" +
	"\x17disk_io_write_bytes_sec\x18\b \x01(\x01R\x13diskIoWriteBytesSec\"\xd8\x01\n" +
	"\x0eSyscallPayload\x12!\n" +
	"\fsyscall_name\x18\x01 \x01(\tR\vsyscallName\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x03R\x03pid\x12\x10\n" +
	"\x03tid\x18\x03 \x01(\x03R\x03tid\x12\x1f\n" +
	"\vduration_ns\x18\x04 \x01(\x03R\n" +
	"durationNs\x12\x1f\n" +
	"\vreturn_code\x18\x05 \x01(\x05R\n" +
	"returnCode\x12\x1c\n" +
	"\targuments\x18\x06 \x01(\fR\targuments\x12\x1f\n" +
	"\vstack_trace\x18\a \x01(\tR\n" +
	"stackTrace\"\xf8\x02\n" +
	"\x0eNetworkPayload\x12#\n" +
	"\rlocal_address\x18\x01 \x01(\tR\flocalAddress\x12\x1d\n" +
	"\n" +
	"local_port\x18\x02 \x01(\x05R\tlocalPort\x12%\n" +
	"\x0eremote_address\x18\x03 \x01(\tR\rremoteAddress\x12\x1f\n" +
	"\vremote_port\x18\x04 \x01(\x05R\n" +
	"remotePort\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12J\n" +
	"\tdirection\x18\x06 \x01(\x0e2,.aegis.telemetry.v1.NetworkPayload.DirectionR\tdirection\x12+\n" +
	"\x11bytes_transferred\x18\a \x01(\x03R\x10bytesTransferred\x12\x1d\n" +
	"\n" +
	"latency_ns\x18\b \x01(\x03R\tlatencyNs\"&\n" +
	"\tDirection\x12\v\n" +
	"\aINBOUND\x10\x00\x12\f\n" +
	"\bOUTBOUND\x10\x01\"\xe6\x02\n" +
	"\fAnomalyEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12E\n" +
	"\bseverity\x18\x03 \x01(\x0e2).aegis.telemetry.v1.AnomalyEvent.SeverityR\bseverity\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12J\n" +
	"\bmetadata\x18\x05 \x03(\v2..aegis.telemetry.v1.AnomalyEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\bSeverity\x12\b\n" +
	"\x04INFO\x10\x00\x12\v\n" +
	"\aWARNING\x10\x01\x12\f\n" +
	"\bCRITICAL\x10\x02\"\xf9\x01\n" +
	"\x11TelemetryResponse\x12D\n" +
	"\x06action\x18\x01 \x01(\x0e2,.aegis.telemetry.v1.TelemetryResponse.ActionR\x06action\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x14throttle_interval_ms\x18\x03 \x01(\x05R\x12throttleIntervalMs\"R\n" +
	"\x06Action\x12\a\n" +
	"\x03ACK\x10\x00\x12\r\n" +
	"\tSLOW_DOWN\x10\x01\x12\r\n" +
	"\tFLUSH_NOW\x10\x02\x12\n" +
	"\n" +
	"\x06RESUME\x10\x03\x12\x15\n" +
	"\x11DROP_LOW_PRIORITY\x10\x04\"\xab\x01\n" +
	"\fFlushRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\"\n" +
	"\rstart_time_ns\x18\x02 \x01(\x03R\vstartTimeNs\x12\x1e\n" +
	"\vend_time_ns\x18\x03 \x01(\x03R\tendTimeNs\x12\x1f\n" +
	"\vevent_types\x18\x04 \x03(\tR\n" +
	"eventTypes\x12\x1b\n" +
	"\tmax_bytes\x18\x05 \x01(\x03R\bmaxBytes\"p\n" +
	"\n" +
	"FlushChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x03R\ttotalSize\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x17\n" +
	"\ais_last\x18\x04 \x01(\bR\x06isLast2\xc9\x01\n" +
	"\x10TelemetryService\x12b\n" +
	"\x0fStreamTelemetry\x12$.aegis.telemetry.v1.TelemetryRequest\x1a%.aegis.telemetry.v1.TelemetryResponse(\x010\x01\x12Q\n" +
	"\vFlushBuffer\x12 .aegis.telemetry.v1.FlushRequest\x1a\x1e.aegis.telemetry.v1.FlushChunk0\x01BW\n" +
	"\x16com.aegis.telemetry.v1B\x0eTelemetryProtoP\x01Z+github.com/aegis/agent/proto/v1;telemetryv1b\x06proto3"

var (
	file_v1_telemetry_proto_rawDescOnce sync.Once
	file_v1_telemetry_proto_rawDescData []byte
)

func file_v1_telemetry_proto_rawDescGZIP() []byte {
	file_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_telemetry_proto_rawDesc), len(file_v1_telemetry_proto_rawDesc)))
	})
	return file_v1_telemetry_proto_rawDescData
}

var file_v1_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_v1_telemetry_proto_goTypes = []any{
	(NetworkPayload_Direction)(0), // 0: aegis.telemetry.v1.NetworkPayload.Direction
	(AnomalyEvent_Severity)(0),    // 1: aegis.telemetry.v1.AnomalyEvent.Severity
	(TelemetryResponse_Action)(0), // 2: aegis.telemetry.v1.TelemetryResponse.Action
	(*AgentMetadata)(nil),         // 3: aegis.telemetry.v1.AgentMetadata
	(*TelemetryRequest)(nil),      // 4: aegis.telemetry.v1.TelemetryRequest
	(*MetricPayload)(nil),         // 5: aegis.telemetry.v1.MetricPayload
	(*SyscallPayload)(nil),        // 6: aegis.telemetry.v1.SyscallPayload
	(*NetworkPayload)(nil),        // 7: aegis.telemetry.v1.NetworkPayload
	(*AnomalyEvent)(nil),          // 8: aegis.telemetry.v1.AnomalyEvent
	(*TelemetryResponse)(nil),     // 9: aegis.telemetry.v1.TelemetryResponse
	(*FlushRequest)(nil),          // 10: aegis.telemetry.v1.FlushRequest
	(*FlushChunk)(nil),            // 11: aegis.telemetry.v1.FlushChunk
	nil,                           // 12: aegis.telemetry.v1.AnomalyEvent.MetadataEntry
}
var file_v1_telemetry_proto_depIdxs = []int32{
	3,  // 0: aegis.telemetry.v1.TelemetryRequest.agent:type_name -> aegis.telemetry.v1.AgentMetadata
	5,  // 1: aegis.telemetry.v1.TelemetryRequest.metric:type_name -> aegis.telemetry.v1.MetricPayload
	6,  // 2: aegis.telemetry.v1.TelemetryRequest.syscall:type_name -> aegis.telemetry.v1.SyscallPayload
	7,  // 3: aegis.telemetry.v1.TelemetryRequest.network:type_name -> aegis.telemetry.v1.NetworkPayload
	8,  // 4: aegis.telemetry.v1.TelemetryRequest.anomaly:type_name -> aegis.telemetry.v1.AnomalyEvent
	0,  // 5: aegis.telemetry.v1.NetworkPayload.direction:type_name -> aegis.telemetry.v1.NetworkPayload.Direction
	1,  // 6: aegis.telemetry.v1.AnomalyEvent.severity:type_name -> aegis.telemetry.v1.AnomalyEvent.Severity
	12, // 7: aegis.telemetry.v1.AnomalyEvent.metadata:type_name -> aegis.telemetry.v1.AnomalyEvent.MetadataEntry
	2,  // 8: aegis.telemetry.v1.TelemetryResponse.action:type_name -> aegis.telemetry.v1.TelemetryResponse.Action
	4,  // 9: aegis.telemetry.v1.TelemetryService.StreamTelemetry:input_type -> aegis.telemetry.v1.TelemetryRequest
	10, // 10: aegis.telemetry.v1.TelemetryService.FlushBuffer:input_type -> aegis.telemetry.v1.FlushRequest
	9,  // 11: aegis.telemetry.v1.TelemetryService.StreamTelemetry:output_type -> aegis.telemetry.v1.TelemetryResponse
	11, // 12: aegis.telemetry.v1.TelemetryService.FlushBuffer:output_type -> aegis.telemetry.v1.FlushChunk
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_v1_telemetry_proto_init() }
func file_v1_telemetry_proto_init() {
	if File_v1_telemetry_proto != nil {
		return
	}
	file_v1_telemetry_proto_msgTypes[1].OneofWrappers = []any{
		(*TelemetryRequest_Metric)(nil),
		(*TelemetryRequest_Syscall)(nil),
		(*TelemetryRequest_Network)(nil),
		(*TelemetryRequest_Anomaly)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_telemetry_proto_rawDesc), len(file_v1_telemetry_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_v1_telemetry_proto_depIdxs,
		EnumInfos:         file_v1_telemetry_proto_enumTypes,
		MessageInfos:      file_v1_telemetry_proto_msgTypes,
	}.Build()
	File_v1_telemetry_proto = out.File
	file_v1_telemetry_proto_goTypes = nil
	file_v1_telemetry_proto_depIdxs = nil
}
