// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: v1/telemetry.proto

package telemetryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelemetryService_StreamTelemetry_FullMethodName = "/aegis.telemetry.v1.TelemetryService/StreamTelemetry"
	TelemetryService_FlushBuffer_FullMethodName     = "/aegis.telemetry.v1.TelemetryService/FlushBuffer"
)

// TelemetryServiceClient is the client API for TelemetryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The core telemetry service for Go Sentinel <-> Scala Brain communication.
type TelemetryServiceClient interface {
	// Bi-directional stream for continuous metrics and backpressure signals.
	// Agents stream telemetry data; Brain responds with acks or throttling commands.
	StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TelemetryRequest, TelemetryResponse], error)
	// On-demand method to retrieve high-fidelity 60-second ring buffer contents.
	// Triggered by the Brain when an anomaly is detected on a peer agent,
	// or by operators via the Aegis CLI/Dashboard.
	FlushBuffer(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FlushChunk], error)
}

type telemetryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryServiceClient(cc grpc.ClientConnInterface) TelemetryServiceClient {
	return &telemetryServiceClient{cc}
}

func (c *telemetryServiceClient) StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TelemetryRequest, TelemetryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TelemetryService_ServiceDesc.Streams[0], TelemetryService_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TelemetryRequest, TelemetryResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetryService_StreamTelemetryClient = grpc.BidiStreamingClient[TelemetryRequest, TelemetryResponse]

func (c *telemetryServiceClient) FlushBuffer(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FlushChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TelemetryService_ServiceDesc.Streams[1], TelemetryService_FlushBuffer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FlushRequest, FlushChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetryService_FlushBufferClient = grpc.ServerStreamingClient[FlushChunk]

// TelemetryServiceServer is the server API for TelemetryService service.
// All implementations must embed UnimplementedTelemetryServiceServer
// for forward compatibility.
//
// The core telemetry service for Go Sentinel <-> Scala Brain communication.
type TelemetryServiceServer interface {
	// Bi-directional stream for continuous metrics and backpressure signals.
	// Agents stream telemetry data; Brain responds with acks or throttling commands.
	StreamTelemetry(grpc.BidiStreamingServer[TelemetryRequest, TelemetryResponse]) error
	// On-demand method to retrieve high-fidelity 60-second ring buffer contents.
	// Triggered by the Brain when an anomaly is detected on a peer agent,
	// or by operators via the Aegis CLI/Dashboard.
	FlushBuffer(*FlushRequest, grpc.ServerStreamingServer[FlushChunk]) error
	mustEmbedUnimplementedTelemetryServiceServer()
}

// UnimplementedTelemetryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelemetryServiceServer struct{}

func (UnimplementedTelemetryServiceServer) StreamTelemetry(grpc.BidiStreamingServer[TelemetryRequest, TelemetryResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedTelemetryServiceServer) FlushBuffer(*FlushRequest, grpc.ServerStreamingServer[FlushChunk]) error {
	return status.Error(codes.Unimplemented, "method FlushBuffer not implemented")
}
func (UnimplementedTelemetryServiceServer) mustEmbedUnimplementedTelemetryServiceServer() {}
func (UnimplementedTelemetryServiceServer) testEmbeddedByValue()                          {}

// UnsafeTelemetryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryServiceServer will
// result in compilation errors.
type UnsafeTelemetryServiceServer interface {
	mustEmbedUnimplementedTelemetryServiceServer()
}

func RegisterTelemetryServiceServer(s grpc.ServiceRegistrar, srv TelemetryServiceServer) {
	// If the following call panics, it indicates UnimplementedTelemetryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelemetryService_ServiceDesc, srv)
}

func _TelemetryService_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TelemetryServiceServer).StreamTelemetry(&grpc.GenericServerStream[TelemetryRequest, TelemetryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetryService_StreamTelemetryServer = grpc.BidiStreamingServer[TelemetryRequest, TelemetryResponse]

func _TelemetryService_FlushBuffer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FlushRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TelemetryServiceServer).FlushBuffer(m, &grpc.GenericServerStream[FlushRequest, FlushChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetryService_FlushBufferServer = grpc.ServerStreamingServer[FlushChunk]

// TelemetryService_ServiceDesc is the grpc.ServiceDesc for TelemetryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aegis.telemetry.v1.TelemetryService",
	HandlerType: (*TelemetryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTelemetry",
			Handler:       _TelemetryService_StreamTelemetry_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "FlushBuffer",
			Handler:       _TelemetryService_FlushBuffer_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "v1/telemetry.proto",
}
